#!/usr/bin/env python

import sys
import rospy
import moveit_commander
import moveit_msgs.msg

class CyclePoses():
    def __init__(self):
        moveit_commander.roscpp_initialize(sys.argv)
        rospy.init_node('up1_cycle_poses', anonymous=True)

        group = moveit_commander.MoveGroupCommander("right_arm")

        # display_trajectory_publisher = rospy.Publisher(
        #         '/move_group/display_planned_path',
        #         moveit_msgs.msg.DisplayTrajectory,
        #         queue_size=10)

        group.set_named_target('pick_up')
        plan = group.plan()
        # rospy.sleep(5)
        group.execute(plan)

	rospy.sleep(5)

	group.set_named_target('pick_left')
	plan = group.plan()
	group.execute(plan)

	rospy.sleep(2)

	group.set_named_target('pick_up')
	plan = group.plan()
	group.execute(plan)

	rospy.sleep(2)

	group.set_named_target('place_right')
	plan = group.plan()
	group.execute(plan)

        moveit_commander.roscpp_shutdown()

if __name__ == '__main__':
    try:
        cycle_poses = CyclePoses()
    except rospy.ROSInterruptException:
        pass
