#!/usr/bin/env python

import rospy
import roslib

from geometry_msgs.msg import Twist

class DriveSquare:
    def __init__(self):
        rospy.init_node('up1_square')
        rospy.on_shutdown(self.cleanup)

        self.pub = rospy.Publisher('cmd_vel', Twist)
        rospy.sleep(1)

        rate = rospy.Rate(5.0)
        while not rospy.is_shutdown():
            # forward
            twist = Twist()
            twist.linear.x = 0.15
            # 10*5hz = 2sec
            for i in range(10):
                self.pub.publish(twist)
                rate.sleep()

            # turn
            twist = Twist()
            # 45 deg/s * 2sec = 90 degrees
            twist.angular.z = 1.57 / 2
            # 10*5hz = 2sec
            for i in range(10):
                self.pub.publish(twist)
                rate.sleep()

    def cleanup(self):
        twist = Twist()
        self.pub.publish(twist)

if __name__=="__main__":
    try:
        square = DriveSquare()
    except rospy.ROSInterruptException:
        pass
