#!/usr/bin/env python

import sys
import rospy
import moveit_commander
import moveit_msgs.msg

class RandomPose():
    def __init__(self):
        moveit_commander.roscpp_initialize(sys.argv)
        rospy.init_node('up1_random_pose', anonymous=True)

        group = moveit_commander.MoveGroupCommander("right_arm")

        # display_trajectory_publisher = rospy.Publisher(
        #         '/move_group/display_planned_path',
        #         moveit_msgs.msg.DisplayTrajectory,
        #         queue_size=10)

        group.set_pose_target(group.get_random_pose())
        plan = group.plan()
        # rospy.sleep(5)
        group.execute(plan)

        moveit_commander.roscpp_shutdown()

if __name__ == '__main__':
    try:
        random_pose = RandomPose()
    except rospy.ROSInterruptException:
        pass
