#!/usr/bin/env python

import sys
import copy
import rospy
import moveit_commander
import moveit_msgs.msg
import geometry_msgs.msg

from std_msgs.msg import String

class TeleopTwistJoy():
    def __init__(self):
        self.msg = """
        ***************************************************
        *                                                 *
        * Press 'X' button to enable wheels.              *
        * Use left analog stick to drive.                 *
        *                                                 *
        ***************************************************
        """

        rospy.init_node('teleop_gripper_joy')

        # ros params
        self.axis_linear = rospy.get_param('axis_linear', 1)
        self.scale_linear = rospy.get_param('scale_linear', 0.7)
        self.scale_linear_turbo = rospy.get_param('scale_linear_turbo', 1.5)

        self.axis_angular = rospy.get_param('axis_angular', 0)
        self.scale_angular = rospy.get_param('scale_angular', 0.4)

        self.enable_button = rospy.get_param('enable_button', 2)
        self.enable_turbo_button = rospy.get_param('enable_turbo_button', 5)

        self.open_button = rospy.get_param('open_button', 3)
        self.close_button = rospy.get_param('close_button', 0)

        self.sent_disable_msg = False

        rospy.Subscriber('joy', Joy, self.callback)
        self.cmd_vel_pub = rospy.Publisher('cmd_vel', Twist, queue_size=10)

        ## Instantiate a RobotCommander object.  This object is an interface to
        ## the robot as a whole.
        robot = moveit_commander.RobotCommander()

        ## Instantiate a PlanningSceneInterface object.  This object is an interface
        ## to the world surrounding the robot.
        scene = moveit_commander.PlanningSceneInterface()

        ## Instantiate a MoveGroupCommander object.  This object is an interface
        ## to one group of joints.  In this case the group is the joints in the left
        ## arm.  This interface can be used to plan and execute motions on the left
        ## arm.
        group = moveit_commander.MoveGroupCommander("right_gripper")

        print self.msg

        rospy.spin()


    def callback(self, joy_msg):
        twist = Twist()

        if joy_msg.buttons[self.enable_turbo_button]:
            twist.linear.x = joy_msg.axes[self.axis_linear] * self.scale_linear_turbo
            twist.angular.z = joy_msg.axes[self.axis_angular] * self.scale_angular
            self.cmd_vel_pub.publish(twist)
            self.sent_disable_msg = False

        elif joy_msg.buttons[self.enable_button]:
            twist.linear.x = joy_msg.axes[self.axis_linear] * self.scale_linear
            twist.angular.z = joy_msg.axes[self.axis_angular] * self.scale_angular
            self.cmd_vel_pub.publish(twist)
            self.sent_disable_msg = False

        elif self.sent_disable_msg == False:
            # When enable button is released, immediately send a single no-motion command
            # in order to stop the robot.
            self.cmd_vel_pub.publish(twist)
            self.sent_disable_msg = True

if __name__ == '__main__':
    teleopTwistJoy = TeleopTwistJoy()
