<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="up1">

  <xacro:include filename="$(find up1_description)/urdf/base_module/wheel.xacro" />
  <xacro:include filename="$(find up1_description)/urdf/base_module/base_module.gazebo.xacro" />

  <xacro:property name="wheel_radius" value="0.03999" />

  <xacro:macro name="base_module">
    <!-- ============================   Base Module   ============================ -->

    <!-- Base Link -->
    <joint name="up1_footprint_joint" type="fixed">
      <origin xyz="0 0 ${wheel_radius + wheel_offset_z}" rpy="0 0 0" />
      <child link="base_link" />
      <parent link="up1_footprint"/>
    </joint>
    <link name="base_link">
      <visual>
        <geometry>
          <mesh filename="package://up1_description/meshes/base/base_viz.dae" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="dark grey" />
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://up1_description/meshes/base/base.stl" scale="0.001 0.001 0.001" />
        </geometry>
      </collision>
      <inertial>
        <mass value="0.30813"/>
        <inertia ixx="0.00175941073" ixy="0.00000172768" ixz="-0.00008279443"
                 iyy="0.00172024238" iyz="0.00000045789" izz="0.00311278092"/>
      </inertial>
    </link>

    <xacro:base_module_gazebo />

    <xacro:wheel prefix="right" end="front" reflect="-1" wheel_offset_x="0.05605" />
    <xacro:wheel prefix="right" end="back" reflect="-1" wheel_offset_x="-0.05848" />
    <xacro:wheel prefix="left" end="front" reflect="1" wheel_offset_x="0.05605" />
    <xacro:wheel prefix="left" end="back" reflect="1" wheel_offset_x="-0.05848" />

  </xacro:macro>

</robot>
