controller_list:
  - name: fake_right_arm_controller
    joints:
      - right_armroot_to_armlink1
      - right_armlink1_to_armlink2
      - right_armlink2_to_armlink3
      - right_armlink3_to_armlink4
      - right_armlink4_to_gripper
  - name: fake_right_gripper_controller
    joints:
      - right_armlink4_to_gripper
      - right_finger_joint